backend:
  name: git-gateway
  branch: main

media_folder: "public/media"

collections:
  - label: "Pages"
    name: "pages"
    files:
      - name: "hello"
        label: "Hello"
        file: "_site/pages/hello.yml"
        fields:
          - {label: "Photo", name: "photo", widget: "image"}
          - {label: "Blurb", name: "body", widget: "markdown"}

      - name: "performance"
        label: "Performance"
        file: "_site/pages/performance.yml"
        fields:
          - {label: "Resume", name: "resume", widget: "image"}
          - label: "Links"
            name: "links"
            widget: "list"
            fields:
              - {label: "Description", name: "description", widget: string}
              - {label: "Link", name: "link", widget: string}

      - name: "writing"
        label: "Writing"
        file: "_site/pages/writing.yml"
        fields:
          - {label: "Blurb", name: "body", widget: "markdown"}
          - label: "Links"
            name: "links"
            widget: "list"
            fields:
              - {label: "Description", name: "description", widget: string}
              - {label: "Link", name: "link", widget: string}
